class HospitalApp{
constructor(){
this.m=new Date().getMonth();this.mn=AM[this.m];
const n=new Date();this.today=`${n.getFullYear()}-${String(n.getMonth()+1).padStart(2,'0')}-${String(n.getDate()).padStart(2,'0')}`;
this.res=[];this.oncRows=[];this.oncHeaders=[];this.evalData=[];this.linksData=[];this.qaData=[];this._resHeaders=[];this._resRaw=null;
this.filterJoined=false;this.filterSpecialty='';this.filterShift='';this.currentMyInfo=null;
this.selectedResidents=new Set();this.currentDisplayMonth=this.m;this.currentShiftsMonth=this.m;this.userSelectedShiftsMonth=false;
this._id=false;this._lrs='';this._dataReady=false;
this.init();
}
init(){
document.getElementById('navContainer').innerHTML=buildNav();
document.getElementById('mainContent').innerHTML=buildMainContent();
const yel=document.getElementById('currentYear');if(yel)yel.textContent=new Date().getFullYear();
document.getElementById('currentDateHeader').textContent=new Date().toLocaleDateString('ar-SA',{weekday:'long',year:'numeric',month:'long',day:'numeric'});
document.getElementById('oncallDatePicker').value=this.today;
document.getElementById('monthSelector').value=this.m;
document.getElementById('oncallMonthTitle').textContent=this.m+1;
this.setupTabs();this.setupSearches();this.setupBackToTop();
this.showLoading(false);
this.loadData();
setInterval(()=>{if(!document.hidden)this.loadData()},120000);
}
async loadData(){
const cached=this.loadFromCache();
if(cached){
this.applyCachedData(cached);
if(!this._dataReady){this._dataReady=true;this.showLoading(true)}
this.loadFresh(true);
return;
}
this.updateProgress(15,'جاري جلب البيانات...');
await this.loadFresh(false);
if(!this._dataReady){this._dataReady=true;this.showLoading(true)}
}
applyCachedData(c){
if(c.residents){this.renderRes(c.residents);this.buildFilters();this.renderShiftsFromResidents()}
if(c.oncall){this.parseOncallData(c.oncall);this.renderMonthlyCalendar();this.showOncallDate(this.today)}
if(c.evaluation)this.evalData=c.evaluation;
if(c.links)this.linksData=c.links;
if(c.qa)this.qaData=c.qa;
this.updateTime();
}
setupBackToTop(){const b=document.getElementById('backToTop');window.addEventListener('scroll',()=>{if(window.scrollY>300)b.classList.add('show');else b.classList.remove('show')},{passive:true})}
showLoading(s){const ls=document.getElementById('loadingScreen');if(s){ls.classList.add('hidden');setTimeout(()=>ls.style.display='none',400)}else{ls.style.display='flex';ls.classList.remove('hidden')}}
updateProgress(p,txt){document.getElementById('progressBar').style.width=p+'%';document.getElementById('loaderPercentage').textContent=p+'%';if(txt)document.getElementById('loaderSubtitle').textContent=txt;if(p>=100)setTimeout(()=>this.showLoading(true),150)}
setupTabs(){
document.querySelectorAll('.nav-btn').forEach(b=>b.addEventListener('click',()=>{
document.querySelectorAll('.nav-btn').forEach(x=>x.classList.remove('active'));
document.querySelectorAll('.tab-content').forEach(x=>x.classList.remove('active'));
b.classList.add('active');
const tid=b.dataset.tab+'-tab';const el=document.getElementById(tid);if(el)el.classList.add('active');
localStorage.setItem('activeTab',b.dataset.tab);
if(b.dataset.tab==='evaluation')this.renderEval();
if(b.dataset.tab==='links')this.renderLinks();
if(b.dataset.tab==='qa')this.renderQA();
if(b.dataset.tab==='shifts')this.renderShiftsFromResidents();
}));
const st=localStorage.getItem('activeTab');if(st){const btn=document.querySelector(`[data-tab="${st}"]`);if(btn)btn.click()}
}
setupSearches(){
document.getElementById('residentSearch').addEventListener('input',debounce(e=>{this._lrs=e.target.value;this.displayResidents();this.updateResCount();this.refreshSelectionUI()},120));
document.getElementById('shiftSearch').addEventListener('input',debounce(e=>this.filterShf(e.target.value),120));
document.getElementById('myInfoSearch').addEventListener('input',debounce(e=>this.searchMe(e.target.value),130));
document.getElementById('evalSearch').addEventListener('input',debounce(e=>this.filterEval(e.target.value),120));
document.getElementById('qaSearch').addEventListener('input',debounce(e=>this.filterQA(e.target.value),120));
}
loadFromCache(){try{const r=localStorage.getItem(CK);if(!r)return null;const d=JSON.parse(r);if(!d.timestamp||(Date.now()-d.timestamp)>CD)return null;return d}catch(e){return null}}
saveToCache(){try{const d={timestamp:Date.now(),residents:this._resRaw||null,oncall:this._oncRaw||null,evaluation:this.evalData||null,links:this.linksData||null,qa:this.qaData||null};localStorage.setItem(CK,JSON.stringify(d))}catch(e){}}
async loadFresh(silent){
try{
const[rd,od,ed,ld,qd]=await Promise.all([this.fetchCSV(GID_R),this.fetchJSON(GID_O),this.fetchCSV(GID_E),this.fetchCSV(GID_L),this.fetchJSON(GID_Q)]);
this._resRaw=rd;this._oncRaw=od;
if(!silent)this.updateProgress(60,'جاري عرض البيانات...');
if(rd){this.renderRes(rd);this.buildFilters();this.renderShiftsFromResidents()}
if(od){this.parseOncallData(od);this.renderMonthlyCalendar();this.showOncallDate(this.today)}
if(ed)this.evalData=ed;
if(ld)this.linksData=ld;
if(qd)this.qaData=qd;
this.saveToCache();
if(!silent)this.updateProgress(100,'تم التحميل');
this.updateTime();
}catch(e){console.error(e);if(!silent)this.updateProgress(100,'تعذر الاتصال')}
}
async fetchCSV(gid){const url=`https://docs.google.com/spreadsheets/d/${SID}/gviz/tq?tqx=out:csv&gid=${gid}`;try{const r=await fetch(url);if(!r.ok)return null;const b=await r.arrayBuffer();const t=new TextDecoder('utf-8').decode(b);if(t.includes('<!DOCTYPE')||t.includes('<html'))return null;return this.parseCSV(t)}catch(e){return null}}
async fetchJSON(gid){const url=`https://docs.google.com/spreadsheets/d/${SID}/gviz/tq?tqx=out:json&gid=${gid}`;try{const r=await fetch(url);if(!r.ok)return null;const raw=await r.text();const s=raw.indexOf('{');const e=raw.lastIndexOf('}')+1;if(s===-1||e===0)return null;const json=JSON.parse(raw.substring(s,e));if(!json||!json.table)return null;const cols=json.table.cols||[];const rows=json.table.rows||[];const result=[];const headers=[];for(const c of cols)headers.push(c.label||'');result.push(headers);for(const row of rows){const cells=row.c||[];const rd=[];for(const cell of cells){if(cell&&cell.v!==null&&cell.v!==undefined)rd.push(String(cell.v));else rd.push('')}if(rd.some(v=>v!==''))result.push(rd)}return result}catch(e){return null}}
parseCSV(text){const result=[];const lines=text.split(/\r?\n/);let cr=[],cf='',iq=false,ce=0;for(let i=0;i<lines.length;i++){const line=lines[i];if(iq){const qi=line.indexOf('"');if(qi!==-1){cf+='\n'+line.substring(0,qi);iq=false;cr.push(cf);cf='';const rest=line.substring(qi+1);if(rest.startsWith(',')){const rf=this.parseCSVLine(rest.substring(1));for(const f of rf)cr.push(f)}if(cr.some(c=>c!=='')){result.push(cr);ce=0}else{ce++;if(ce>=10)break}cr=[]}else{cf+='\n'+line}continue}const fields=this.parseCSVLine(line);if(fields.some(c=>c!=='')){result.push(fields);ce=0}else{ce++;if(ce>=10)break}}if(cr.length&&cr.some(c=>c!==''))result.push(cr);return result}
parseCSVLine(line){const fields=[];let c='',iq=false;for(let i=0;i<line.length;i++){const ch=line[i];if(ch==='"'){if(iq){if(i+1<line.length&&line[i+1]==='"'){c+='"';i++}else iq=false}else iq=true}else if(ch===','&&!iq){fields.push(c);c=''}else c+=ch}fields.push(c);return fields}
getShiftColIndex(headers,month){const cm=month!==undefined?month:this.m+1;for(let i=12;i<headers.length;i++){const h=(headers[i]||'').trim();const m=h.match(/فرز\s+شهر\s+(\d+)/i);if(m&&parseInt(m[1])===cm)return i}return -1}
getShiftFromRow(r,month){const h=this._resHeaders||[];const idx=this.getShiftColIndex(h,month);if(idx<0)return'';return(r[idx]||'').trim()}
getAllShiftMonths(){const h=this._resHeaders||[];const months=[];for(let i=12;i<h.length;i++){const ht=(h[i]||'').trim();const m=ht.match(/فرز\s+شهر\s+(\d+)/i);if(m)months.push({month:parseInt(m[1]),col:i,label:ht})}return months.sort((a,b)=>a.month-b.month)}
isFutureShiftMonthAutoCopy(month){const current=this.m+1;if(month<=current)return false;const h=this._resHeaders||[];const idx=this.getShiftColIndex(h,month);const prev=month===1?12:month-1;const pidx=this.getShiftColIndex(h,prev);if(idx<0||pidx<0||!this._resRaw||this._resRaw.length<2)return false;let compared=0,same=0,hasMeaningful=false;for(let i=1;i<this._resRaw.length;i++){const r=this._resRaw[i];if(!r||!r[1]||!r[1].trim())continue;const status=(r[11]||'').trim();if(!isJoined(status))continue;const cur=(r[idx]||'').trim();const prv=(r[pidx]||'').trim();if(!cur&&!prv)continue;if(cur&&cur!=='غير محدد')hasMeaningful=true;compared++;if(cur===prv)same++}return hasMeaningful&&compared>=10&&same===compared}
hasShiftDataForMonth(month){const h=this._resHeaders||[];const idx=this.getShiftColIndex(h,month);if(idx<0||!this._resRaw||this._resRaw.length<2)return false;if(this.isFutureShiftMonthAutoCopy(month))return false;for(let i=1;i<this._resRaw.length;i++){const r=this._resRaw[i];if(!r)continue;const v=(r[idx]||'').trim();if(v&&v!=='غير محدد')return true}return false}
getPreferredShiftMonth(){const allMonths=this.getAllShiftMonths();if(!allMonths.length)return this.m+1;const current=this.m+1;const next=current===12?1:current+1;if(this.hasShiftDataForMonth(next))return next;if(this.hasShiftDataForMonth(current))return current;const withData=allMonths.filter(m=>this.hasShiftDataForMonth(m.month));if(withData.length)return withData[withData.length-1].month;return allMonths[allMonths.length-1].month}
renderShiftsFromResidents(){
const allMonths=this.getAllShiftMonths();
if(!this.userSelectedShiftsMonth){this.currentShiftsMonth=this.getPreferredShiftMonth()-1}
const sel=document.getElementById('shiftsMonthSelector');
if(sel){sel.innerHTML=allMonths.map(m=>`<option value="${m.month}"${m.month===this.currentShiftsMonth+1?' selected':''}>${m.label||('فرز شهر '+m.month)}</option>`).join('')}
this.dispShiftsByMonth(this.currentShiftsMonth+1);
}
changeShiftsMonth(){const sel=document.getElementById('shiftsMonthSelector');if(!sel)return;this.userSelectedShiftsMonth=true;this.currentShiftsMonth=parseInt(sel.value)-1;this.dispShiftsByMonth(parseInt(sel.value));}
dispShiftsByMonth(month){
const h=this._resHeaders||[];const idx=this.getShiftColIndex(h,month);
const g=document.getElementById('shiftsGrid');if(!g)return;g.innerHTML='';
document.getElementById('shiftMonthName').textContent=AM[month-1];
if(idx<0||!this._resRaw||this._resRaw.length<2||this.isFutureShiftMonthAutoCopy(month)){g.innerHTML='<p style="text-align:center;color:#888;padding:30px;">لا توجد بيانات فروز لهذا الشهر</p>';return}
const groups={};
for(let i=1;i<this._resRaw.length;i++){const r=this._resRaw[i];if(!r||!r[1]||!r[1].trim())continue;const status=(r[11]||'').trim();if(!isJoined(status))continue;const sVal=(r[idx]||'').trim();if(!sVal||sVal==='غير محدد')continue;const abbr=(r[2]||'').trim();const name=(r[1]||'').trim();const phone=(r[4]||'').trim();if(!groups[sVal])groups[sVal]=[];groups[sVal].push({name,abbr,phone})}
const sGroups=Object.entries(groups).sort((a,b)=>b[1].length-a[1].length);
if(sGroups.length===0){g.innerHTML='<p style="text-align:center;color:#888;padding:30px;">لا توجد بيانات فروز للطلاب الملتحقين لهذا الشهر</p>';return}
sGroups.forEach(([shiftName,members])=>{
const c=document.createElement('div');c.className='shift-card-full';
let mh='';if(members.length>0){const nwc=members.map(m=>`<li>${mcn(m.name,m.phone,m.abbr)}</li>`).join('');mh=`<div class="names-dropdown"><button class="names-dropdown-btn"><span><i class="fas fa-users"></i> الأطباء الملتحقين (${members.length})</span><i class="fas fa-chevron-down"></i></button><ul class="names-dropdown-content">${nwc}</ul></div>`}
c.innerHTML=`<h3><i class="fas fa-clipboard-list"></i> ${shiftName}</h3><div class="shift-stats"><div class="shift-stat"><div class="num">${members.length}</div><div class="lbl">عدد الأطباء الملتحقين</div></div></div>${mh}`;
g.appendChild(c);
});
}
toggleSelectAll(){const list=this.getFilteredList();if(this.selectedResidents.size===list.length&&list.length>0)this.selectedResidents.clear();else list.forEach(r=>this.selectedResidents.add(r.name));this.refreshSelectionUI()}
toggleResident(name){if(this.selectedResidents.has(name))this.selectedResidents.delete(name);else this.selectedResidents.add(name);this.refreshSelectionUI()}
getFilteredList(){let list=this.res;if(this.filterJoined)list=list.filter(r=>isJoined(r.st));if(this.filterSpecialty)list=list.filter(r=>r.spec===this.filterSpecialty);if(this.filterShift)list=list.filter(r=>r.monthlyShift===this.filterShift);if(this._lrs){const t=this._lrs;list=list.filter(r=>smartSearch(r.name+' '+r.abbr,t))}return list}
refreshSelectionUI(){const list=this.getFilteredList();const total=this.res.length;const joined=this.res.filter(r=>isJoined(r.st)).length;document.getElementById('selectedCount').textContent=this.selectedResidents.size+' محدد';const btn=document.getElementById('exportContactsBtn');btn.disabled=this.selectedResidents.size===0;const sab=document.querySelector('.select-all-btn');if(this.selectedResidents.size===list.length&&list.length>0)sab.innerHTML='<i class="fas fa-square"></i> إلغاء الكل';else sab.innerHTML='<i class="fas fa-check-square"></i> تحديد الكل';document.querySelectorAll('.contact-checkbox').forEach(cb=>{cb.checked=this.selectedResidents.has(cb.dataset.name)});const pb=document.getElementById('joinedPercentageBadge');if(this.filterJoined&&total>0){pb.textContent=Math.round((joined/total)*100)+'% ('+joined+'/'+total+')';pb.style.display='inline-block'}else pb.style.display='none'}
exportToContacts(){const sel=this.res.filter(r=>this.selectedResidents.has(r.name)&&r.phone);if(!sel.length)return;let vcf='';for(const r of sel){const np=r.name.split(' ');const ln=np.pop()||'';const fn=np.shift()||'';const mn=np.join(' ');vcf+='BEGIN:VCARD\nVERSION:3.0\nFN:'+r.name+'\nN:'+ln+';'+fn+';'+mn+';;\nTEL;TYPE=MOBILE:'+r.phone+'\nEND:VCARD\n'}const blob=new Blob([vcf],{type:'text/vcard;charset=utf-8'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.setAttribute('href',url);a.setAttribute('download','contacts.vcf');a.style.display='none';document.body.appendChild(a);a.click();setTimeout(()=>{document.body.removeChild(a);URL.revokeObjectURL(url);showToast('تم تحميل جهات الاتصال!')},500)}
renderRes(d){this.res=[];const tb=document.getElementById('residentsBody');const cd=document.getElementById('residentsCards');if(!d||d.length<2){if(tb)tb.innerHTML='<tr><td colspan="10" style="text-align:center;padding:40px;">لا توجد بيانات</td></tr>';this.updateResCount();return}const headers=d[0]||[];this._resHeaders=headers;for(let i=1;i<d.length;i++){const r=d[i];if(!r[1]||!r[1].trim()||r[1].includes('الاسم'))continue;const res={seq:i+1,name:(r[1]||'').trim(),abbr:(r[2]||'').trim(),spec:(r[3]||'').trim(),phone:(r[4]||'').trim(),join:(r[9]||'').trim(),onc:(r[10]||'').trim(),cumulativeOnc:(r[10]||'').trim(),st:(r[11]||'').trim(),monthlyShift:this.getShiftFromRow(r)};if(!res.name)continue;this.res.push(res)}this.displayResidents()}
displayResidents(){const tb=document.getElementById('residentsBody');const cd=document.getElementById('residentsCards');if(!tb||!cd)return;tb.innerHTML='';cd.innerHTML='';const list=this.getFilteredList();const fg=document.createDocumentFragment();list.forEach(res=>{const ok=isJoined(res.st);const checked=this.selectedResidents.has(res.name)?'checked':'';const statusClass=getStatusBadgeClass(res.st);const tr=document.createElement('tr');tr.innerHTML=`<td class="seq-cell">${res.seq}</td><td><input type="checkbox" class="contact-checkbox" data-name="${res.name.replace(/"/g,'&quot;')}" ${checked} onchange="app.toggleResident('${res.name.replace(/'/g,"\\'")}')"></td><td style="text-align:right;">${mcn(res.name,res.phone)}</td><td>${res.abbr}</td><td>${res.spec}</td><td><span dir="ltr">${res.phone}</span> <button class="copy-btn" onclick="copyPhone('${res.phone}',this)"><i class="fas fa-copy"></i></button></td><td>${res.monthlyShift||'-'}</td><td>${res.join||'-'}</td><td>${res.onc||'-'}</td><td><span class="status-badge ${ok?'status-joined':statusClass}">${ok?'<i class="fas fa-circle-check"></i>':'<i class="fas fa-hourglass-half"></i>'} ${res.st||'غير محدد'}</span></td>`;fg.appendChild(tr);const c=document.createElement('div');c.className='resident-card';c.innerHTML=`<div style="display:flex;align-items:center;gap:8px;margin-bottom:8px;flex-wrap:wrap;"><span class="seq-badge">${res.seq}</span><input type="checkbox" class="contact-checkbox" data-name="${res.name.replace(/"/g,'&quot;')}" ${checked} onchange="app.toggleResident('${res.name.replace(/'/g,"\\'")}')"><div class="card-header" style="flex:1;margin:0;padding:0;border:none;min-width:0;"><span class="card-name" style="word-break:break-word;">${mcn(res.name,res.phone)}</span><span class="card-abbr">${res.abbr}</span></div></div><div class="card-row"><span class="card-label">الاختصاص</span><span class="card-value">${res.spec}</span></div><div class="card-row"><span class="card-label">الهاتف</span><span class="card-value"><span dir="ltr">${res.phone}</span> <button class="copy-btn" onclick="copyPhone('${res.phone}',this)"><i class="fas fa-copy"></i></button></span></div><div class="card-row"><span class="card-label">الفرز</span><span class="card-value">${res.monthlyShift||'-'}</span></div><div class="card-row"><span class="card-label">الالتحاق</span><span class="card-value">${res.join||'-'}</span></div><div class="card-row"><span class="card-label">المناوبات</span><span class="card-value">${res.onc||'-'}</span></div><div class="card-row"><span class="card-label">الحالة</span><span class="card-value"><span class="status-badge ${ok?'status-joined':statusClass}">${ok?'<i class="fas fa-circle-check"></i>':'<i class="fas fa-hourglass-half"></i>'} ${res.st||'غير محدد'}</span></span></div>`;cd.appendChild(c)});tb.appendChild(fg);this.updateResCount();this.refreshSelectionUI()}
updateResCount(){const list=this.getFilteredList();const total=this.res.length;const joined=this.res.filter(r=>isJoined(r.st)).length;const ce=document.getElementById('residentCount');if(ce)ce.textContent=list.length+' مقيم';const pb=document.getElementById('joinedPercentageBadge');if(this.filterJoined&&total>0){pb.textContent=Math.round((joined/total)*100)+'% ('+joined+'/'+total+')';pb.style.display='inline-block'}else pb.style.display='none'}
buildFilters(){const ss=document.getElementById('specialtyFilter');const sf=document.getElementById('shiftFilter');if(!ss||!sf)return;const specs=[...new Set(this.res.map(r=>r.spec).filter(s=>s))].sort();const shifts=[...new Set(this.res.map(r=>r.monthlyShift).filter(s=>s))].sort();ss.innerHTML='<option value="">جميع الاختصاصات</option>'+specs.map(s=>`<option value="${s}">${s}</option>`).join('');ss.value=this.filterSpecialty||'';sf.innerHTML='<option value="">جميع الفروز</option>'+shifts.map(s=>`<option value="${s}">${s}</option>`).join('');sf.value=this.filterShift||''}
filterBySpecialty(){this.filterSpecialty=document.getElementById('specialtyFilter').value;this.selectedResidents.clear();this.displayResidents()}
filterByShift(){this.filterShift=document.getElementById('shiftFilter').value;this.selectedResidents.clear();this.displayResidents()}
toggleFilter(){this.filterJoined=!this.filterJoined;const btn=document.getElementById('filterJoinedBtn');if(this.filterJoined){btn.classList.add('active-filter');btn.innerHTML='<i class="fas fa-filter"></i> إظهار الكل'}else{btn.classList.remove('active-filter');btn.innerHTML='<i class="fas fa-filter"></i> الملتحقين فقط'}this.selectedResidents.clear();this.displayResidents()}
filterShf(term){const t=term.toLowerCase().trim();const cards=document.querySelectorAll('#shiftsGrid .shift-card-full');cards.forEach(c=>{if(!t){c.style.display='';return}c.style.display=c.textContent.toLowerCase().includes(t)?'':'none'})}
renderEval(){
const head=document.getElementById('evalHead');const body=document.getElementById('evalBody');const cards=document.getElementById('evalCards');
if(!head||!body||!cards)return;head.innerHTML='';body.innerHTML='';cards.innerHTML='';
const d=this.evalData;if(!d||d.length<2){body.innerHTML='<tr><td colspan="14" style="text-align:center;padding:40px;">لا توجد بيانات</td></tr>';return}
const lastCol=14;const headers=d[0];let h='<tr>';for(let i=1;i<=lastCol;i++){let hl=headers[i]||'';if(i===13)hl='الثناءات';if(i===14)hl='العقوبات';h+=`<th>${hl}</th>`}h+='</tr>';head.innerHTML=h;
let bh='',ch='';
for(let i=1;i<d.length;i++){const row=d[i];if(!row||!row.length)continue;const isEx=(row[1]||'').trim()==='مثال توضيحي';bh+=`<tr${isEx?' class="example-row"':''}>`;
for(let j=1;j<=lastCol;j++){let cc='';if(j===13)cc=' class="eval-praise-cell"';if(j===14)cc=' class="eval-penalty-cell"';let cv=row[j]||'-';if((j===13||j===14)&&cv&&cv!=='-'&&cv.trim()){cv=`<span class="${j===13?'praise-badge':'penalty-badge'}">${cv}</span>`}bh+=`<td${cc}>${cv}</td>`}bh+='</tr>';
if(i>=3&&!isEx){ch+=`<div class="resident-card"><div class="card-header"><span class="card-name">${row[1]||''} (${row[2]||''})</span><span class="card-abbr">${row[3]||''}</span></div>`;
for(let j=4;j<=lastCol;j++){let hl=headers[j]||'';if(j===13)hl='الثناءات';if(j===14)hl='العقوبات';let cv=row[j]||'-';let cvc='';if(j===13){cvc='color:#27ae60;font-weight:600;';if(cv&&cv!=='-'&&cv.trim())cv=`<span class="praise-badge">${cv}</span>`}if(j===14){cvc='color:#e74c3c;font-weight:600;';if(cv&&cv!=='-'&&cv.trim())cv=`<span class="penalty-badge">${cv}</span>`}ch+=`<div class="card-row"><span class="card-label">${hl}</span><span class="card-value" style="${cvc}">${cv}</span></div>`}ch+='</div>'}}body.innerHTML=bh;cards.innerHTML=ch;this.filterEval(document.getElementById('evalSearch')?.value||'')}
filterEval(term){const t=(term||'').toLowerCase().trim();document.querySelectorAll('#evalBody tr').forEach(r=>{if(!t){r.style.display='';return}r.style.display=r.textContent.toLowerCase().includes(t)?'':'none'});document.querySelectorAll('#evalCards .resident-card').forEach(c=>{if(!t){c.style.display='';return}c.style.display=c.textContent.toLowerCase().includes(t)?'':'none'})}
formatLink(l){if(!l||!l.trim())return'<span style="color:var(--text-secondary);">-</span>';const lt=l.trim();if(lt.startsWith('http'))return`<a href="${lt}" target="_blank" class="link-url"><i class="fas fa-external-link-alt"></i> فتح الرابط</a>`;return`<span style="color:var(--text);font-weight:600;">${lt}</span>`}
renderLinks(){const grid=document.getElementById('linksGrid');if(!grid)return;grid.innerHTML='';const d=this.linksData;if(!d||d.length<2){grid.innerHTML='<p style="text-align:center;color:#888;padding:30px;">لا توجد بيانات</p>';return}let th='<div class="table-wrapper desktop-table"><table><thead><tr><th>ت</th><th>الاسم</th><th>النوع</th><th>الغاية والهدف</th><th>الاعضاء</th><th>رابط الانضمام</th></tr></thead><tbody>';let ch='<div class="mobile-cards">';for(let i=1;i<d.length;i++){const row=d[i];if(!row||!row[1]||!row[1].trim())continue;const seq=row[0]||'',nm=row[1]||'',tp=row[2]||'',pp=row[3]||'',mb=row[4]||'',lk=row[5]||'';th+=`<tr><td style="font-weight:700;color:#667eea;">${seq}</td><td><strong>${nm}</strong></td><td>${tp}</td><td>${pp}</td><td>${mb}</td><td>${this.formatLink(lk)}</td></tr>`;ch+=`<div class="link-card"><span style="font-size:11px;color:var(--text-secondary);">#${seq}</span><div class="link-title"><span class="link-label">الاسم:</span> ${nm}</div>${tp?`<div><span class="link-label">النوع:</span> <span class="link-type">${tp}</span></div>`:''}${pp?`<div class="link-desc"><span class="link-label">الغاية والهدف:</span> ${pp}</div>`:''}${mb?`<div class="link-members"><span class="link-label">الاعضاء:</span> ${mb}</div>`:''}<div style="margin-top:8px;"><span class="link-label">رابط الانضمام:</span> ${this.formatLink(lk)}</div></div>`}th+='</tbody></table></div>';ch+='</div>';grid.innerHTML=th+ch}
renderQA(){const container=document.getElementById('qaContainer');if(!container)return;container.innerHTML='';const d=this.qaData;if(!d||d.length<2){container.innerHTML='<p style="text-align:center;color:#888;padding:30px;">لا توجد أسئلة وأجوبة بعد.</p>';return}const qi=[];for(let i=1;i<d.length;i++){const row=d[i];if(!row||row.length<2)continue;const cat=(row[1]||'').trim(),q=(row[2]||'').trim(),a=(row[3]||'').trim();if(!q||!a||q==='السؤال'||q==='التصنيف'||cat==='التصنيف')continue;qi.push({category:cat||'عام',question:q,answer:a})}if(!qi.length){container.innerHTML='<p style="text-align:center;color:#888;padding:30px;">لا توجد أسئلة وأجوبة بعد.</p>';return}const cats={};qi.forEach(item=>{const c=item.category;if(!cats[c])cats[c]=[];cats[c].push(item)});let h='';Object.keys(cats).sort().forEach(cat=>{h+=`<div class="qa-category-section"><button class="qa-category-header open" onclick="toggleQACategory(this)"><span><i class="fas fa-folder"></i> ${cat} (${cats[cat].length})</span><i class="fas fa-chevron-down"></i></button><div class="qa-category-content show">`;cats[cat].forEach(item=>{h+=`<div class="qa-card"><div class="qa-card-header" onclick="toggleQACard(this.parentElement)"><span class="qa-category-tag">${item.category}</span><span class="qa-question-text">${item.question}</span><i class="fas fa-chevron-down qa-toggle-icon"></i></div><div class="qa-answer">${item.answer}</div></div>`});h+='</div></div>'});container.innerHTML=h;this.filterQA(document.getElementById('qaSearch')?.value||'')}
filterQA(term){const t=(term||'').toLowerCase().trim();document.querySelectorAll('.qa-card').forEach(c=>{if(!t){c.style.display='';return}c.style.display=c.textContent.toLowerCase().includes(t)?'':'none'});document.querySelectorAll('.qa-category-section').forEach(s=>{let hv=false;s.querySelectorAll('.qa-card').forEach(c=>{if(c.style.display!=='none')hv=true});s.style.display=(!t||hv)?'':'none'})}
parseOncallData(d){this.oncRows=[];this.oncHeaders=[];if(!d||d.length<2)return;
const rawHeaders=d[0]||[];
const firstDataRow=d[1]||[];
const isHeaderRow=firstDataRow&&(firstDataRow[0]||'').trim()==='اليوم'&&(firstDataRow[1]||'').includes('Date');
const startIdx=isHeaderRow?2:1;
const headerRow=d[0]||[];
const hasLabels=headerRow.some(h=>h&&h.length>0);
if(hasLabels){this.oncHeaders=headerRow}else{this.oncHeaders=rawHeaders}
document.getElementById('oncallMonthTitle').textContent=this.currentDisplayMonth+1;
for(let i=startIdx;i<d.length;i++){const row=d[i];if(!row||!row.length)continue;
let ds=row[1]||'';
if(!ds)ds=row[0]||'';
const dm=ds.match(/Date\((\d+),\s*(\d+),\s*(\d+)\)/);
if(dm){ds=`${parseInt(dm[1])}-${String(parseInt(dm[2])+1).padStart(2,'0')}-${String(parseInt(dm[3])).padStart(2,'0')}`}else{ds=extractDate(ds)||''}
if(ds)this.oncRows.push({date:ds,day:row[0]||'',row:row})}}
getOncRow(ds){return this.oncRows.find(r=>r.date===ds)||null}
findRbyExact(abbr){if(!abbr)return null;return this.res.find(r=>exactNameMatch(r.abbr,abbr))||this.res.find(r=>exactNameMatch(r.name,abbr))||null}
changeMonth(){this.currentDisplayMonth=parseInt(document.getElementById('monthSelector').value);const yr=parseInt(this.today.split('-')[0]);document.getElementById('oncallDatePicker').value=`${yr}-${String(this.currentDisplayMonth+1).padStart(2,'0')}-01`;document.getElementById('oncallMonthTitle').textContent=this.currentDisplayMonth+1;this.renderMonthlyCalendar();document.getElementById('oncallDayDisplay').innerHTML=''}
selectDayFromCalendar(){const v=document.getElementById('oncallDatePicker').value;if(v){const m=parseInt(v.split('-')[1])-1;if(m!==this.currentDisplayMonth){this.currentDisplayMonth=m;document.getElementById('monthSelector').value=m;document.getElementById('oncallMonthTitle').textContent=m+1;this.renderMonthlyCalendar()}this.showOncallDate(v);setTimeout(()=>{const el=document.getElementById('oncallDayDisplay');if(el)el.scrollIntoView({behavior:'smooth',block:'start'})},200)}}
showOncallDate(ds){const dp=document.getElementById('oncallDayDisplay');const dstr=ds||this.today;if(!dstr||!dp||!this.oncRows.length)return;const oncRow=this.getOncRow(dstr);if(!oncRow){dp.innerHTML=`<div class="oncall-day-card"><h3><i class="fas fa-calendar-day"></i> ${dstr} - ${getDayName(dstr)}</h3><p style="color:#888;">لا توجد مناوبات لهذا التاريخ.</p></div>`;return}const now=new Date();const ts=`${now.getFullYear()}-${String(now.getMonth()+1).padStart(2,'0')}-${String(now.getDate()).padStart(2,'0')} ${String(now.getHours()).padStart(2,'0')}:${String(now.getMinutes()).padStart(2,'0')}:${String(now.getSeconds()).padStart(2,'0')}`;const cats={};for(let col=2;col<this.oncHeaders.length;col++){const cn=this.oncHeaders[col]||'أخرى';const cc=(oncRow.row[col]||'').trim();if(!cc)continue;const names=splitNames(cc);if(!names.length)continue;if(!cats[cn])cats[cn]=[];for(const n of names){const resident=this.findRbyExact(n);const fn=resident?resident.name:n;const ph=resident?resident.phone:'';const ab=resident?resident.abbr:n;if(!cats[cn].find(x=>x.abbr===ab))cats[cn].push({abbr:ab,name:fn,phone:ph,resAbbr:ab})}}const dn=getDayName(dstr);const we=isWeekend(dstr);const catEntries=Object.entries(cats);const catCount=catEntries.length;const totalDoctors=catEntries.reduce((a,[,n])=>a+n.length,0);let h=`<div class="oncall-day-card" id="oncallCardContent"><div class="oncall-card-head"><h3 class="${we?'weekend':''}"><i class="fas fa-calendar-day"></i> ${dstr} - ${dn}${we?' <span class="day-badge weekend">عطلة</span>':''}</h3><div class="oncall-card-stats"><span class="oncall-stat-pill"><i class="fas fa-layer-group"></i> ${catCount} فئة</span><span class="oncall-stat-pill"><i class="fas fa-user-doctor"></i> ${totalDoctors} طبيب</span></div></div><div class="capture-timestamp"><i class="fas fa-clock"></i> ${ts}</div>`;if(!catCount)h+='<p style="color:#888;">لا توجد مناوبات مسجلة لهذا التاريخ.</p>';else{h+='<div class="oncall-categories-grid">';for(const[cn,names]of catEntries){h+=`<div class="oncall-category"><h4><span>${cn}</span><span class="cat-count">${names.length}</span></h4><div class="oncall-names-list">`;for(const n of names)h+=`<span class="oncall-name-tag">${mcn(n.name,n.phone,n.resAbbr)}</span>`;h+='</div></div>'}h+='</div>'}h+=`<div class="oncall-export-actions"><button class="download-btn" onclick="app.downloadOncallImage(false,this)"><i class="fas fa-camera btn-icon"></i><span class="btn-spinner"></span> تحميل المناوبات (عادي)</button><button class="download-btn hq-btn" onclick="app.downloadOncallImage(true,this)"><i class="fas fa-wand-magic-sparkles btn-icon"></i><span class="btn-spinner"></span> تحميل المناوبات (دقة فائقة)</button></div></div>`;dp.innerHTML=h}
setDownloadBtnState(btn,loading){if(!btn)return;btn.classList.toggle('loading',loading);btn.disabled=!!loading}
async _captureImage(el,fn,bg,btn,mode='normal'){if(this._id)return;this._id=true;this.setDownloadBtnState(btn,true);showDownloadProgress('جاري توليد الصورة...');updateDownloadProgress(5);let stage=null;try{await new Promise(requestAnimationFrame);const isOncall=el.id==='oncallCardContent';const isHQ=isOncall&&mode==='hq';const baseW=isOncall?840:920;const dpr=Math.max(1,window.devicePixelRatio||1);const sc=isHQ?Math.min(3.6,Math.max(2.85,dpr*1.35)):(isOncall?Math.min(3.0,Math.max(2.35,dpr*1.2)):Math.min(2.95,Math.max(2.2,dpr*1.2)));stage=document.createElement('div');stage.style.position='fixed';stage.style.left='-10000px';stage.style.top='0';stage.style.zIndex='-1';stage.style.pointerEvents='none';const capNode=el.cloneNode(true);capNode.classList.add('capture-mode');capNode.style.width=baseW+'px';capNode.style.maxWidth=baseW+'px';capNode.style.margin='0';stage.appendChild(capNode);document.body.appendChild(stage);await new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r)));updateDownloadProgress(14);const canvas=await html2canvas(capNode,{backgroundColor:bg,scale:sc,useCORS:true,allowTaint:true,logging:false});updateDownloadProgress(62);const pd=isOncall?20:22;const nc=document.createElement('canvas');nc.width=canvas.width+pd*2;nc.height=canvas.height+pd*2;let ctx=nc.getContext('2d');ctx.fillStyle=bg;ctx.fillRect(0,0,nc.width,nc.height);ctx.drawImage(canvas,pd,pd);const maxSide=isHQ?3400:(isOncall?2850:3500);const side=Math.max(nc.width,nc.height);let outCanvas=nc;if(side>maxSide){const ratio=maxSide/side;outCanvas=document.createElement('canvas');outCanvas.width=Math.round(nc.width*ratio);outCanvas.height=Math.round(nc.height*ratio);const octx=outCanvas.getContext('2d');octx.imageSmoothingEnabled=true;octx.imageSmoothingQuality='high';octx.drawImage(nc,0,0,outCanvas.width,outCanvas.height)}updateDownloadProgress(86);const blob=await new Promise(res=>outCanvas.toBlob(res,'image/png'));if(!blob)throw new Error('PNG export failed');const url=URL.createObjectURL(blob);const link=document.createElement('a');link.download=fn;link.href=url;document.body.appendChild(link);link.click();document.body.removeChild(link);setTimeout(()=>URL.revokeObjectURL(url),1500);updateDownloadProgress(100);setTimeout(()=>{hideDownloadProgress();this._id=false;this.setDownloadBtnState(btn,false);showToast(isHQ?'تم التحميل بدقة فائقة!':'تم التحميل بجودة عالية وبحجم أنسب للمشاركة!')},450)}catch(e){console.error(e);hideDownloadProgress();this._id=false;this.setDownloadBtnState(btn,false);showToast('تعذر توليد الصورة. حاول مرة أخرى.')}finally{if(stage&&stage.parentNode)stage.parentNode.removeChild(stage)}}
downloadOncallImage(hq=false,triggerBtn=null){const el=document.getElementById('oncallCardContent');if(!el)return;const btn=triggerBtn||el.querySelector('.download-btn');const bg=document.body.classList.contains('dark-mode')?'#1e293b':'#ffffff';this._captureImage(el,`مناوبات_${document.getElementById('oncallDatePicker').value||this.today}.png`,bg,btn,hq?'hq':'normal')}
downloadMyInfoImage(){const el=document.getElementById('myInfoContent');if(!el)return;const btn=el.querySelector('.download-btn');const bg=document.body.classList.contains('dark-mode')?'#1e293b':'#ffffff';this._captureImage(el,`${this.currentMyInfo?.name||'معلوماتي'}.png`,bg,btn)}
renderMonthlyCalendar(){const container=document.getElementById('monthlyCalendar');if(!container)return;const yr=parseInt(this.today.split('-')[0]);const mo=this.currentDisplayMonth;const dim=new Date(yr,mo+1,0).getDate();const fd=new Date(yr,mo,1).getDay();const afd=fd===0?6:fd-1;const dns=['اثنين','ثلاثاء','أربعاء','خميس','جمعة','سبت','أحد'];const tn=parseInt(this.today.split('-')[2]);const tm=parseInt(this.today.split('-')[1])-1;let h=`<div class="monthly-calendar"><div class="calendar-header"><h3><i class="fas fa-calendar-days"></i> ${AM[mo]} ${yr}</h3></div><div class="calendar-grid">`;dns.forEach((d,i)=>{h+=`<div class="calendar-day-header${i===4||i===5?' weekend':''}">${d}</div>`});for(let i=0;i<afd;i++)h+='<div class="calendar-day empty"></div>';for(let day=1;day<=dim;day++){const ds=`${yr}-${String(mo+1).padStart(2,'0')}-${String(day).padStart(2,'0')}`;const d=new Date(yr,mo,day);const di=d.getDay();const it=day===tn&&mo===tm;const pa=ds<this.today;let cls='calendar-day';if(it)cls+=' today';if(pa&&!it)cls+=' past-day';if(di===5||di===6)cls+=' weekend';h+=`<div class="${cls}" onclick="app.clickCalendarDay('${ds}')">${day}</div>`}h+='</div></div>';container.innerHTML=h}
clickCalendarDay(ds){document.getElementById('oncallDatePicker').value=ds;this.selectDayFromCalendar()}
searchMe(term){const t=term.toLowerCase().trim();const rl=document.getElementById('searchResultsList');const rd=document.getElementById('myInfoResult');if(t.length<1){rl.innerHTML='';rd.classList.remove('show');return}const mt=this.res.filter(r=>smartSearch(r.name+' '+r.abbr,t));if(!mt.length){rl.innerHTML='<div class="no-results"><i class="fas fa-magnifying-glass"></i> لا يوجد نتائج مطابقة.</div>';rd.classList.remove('show');return}if(mt.length===1){rl.innerHTML='';this.showMe(mt[0])}else{this._sm=mt;rl.innerHTML=mt.map((m,i)=>`<div class="search-result-item" onclick="app.selectMe(${i})"><span><strong>${m.name}</strong> (${m.abbr})</span><span style="color:#667eea;">${m.spec}</span></div>`).join('');rd.classList.remove('show')}}
selectMe(i){if(this._sm&&this._sm[i]){document.getElementById('searchResultsList').innerHTML='';this.showMe(this._sm[i])}}
getEvalForResident(name,abbr){if(!this.evalData||this.evalData.length<4)return null;const headers=this.evalData[0]||[];for(let i=3;i<this.evalData.length;i++){const row=this.evalData[i];if(!row||!row.length)continue;const rn=(row[1]||'').trim(),ra=(row[2]||'').trim();if(smartSearch(rn,name)||smartSearch(ra,abbr)||ra===abbr){return{name:rn,abbr:ra,spec:row[3]||'-',skills:[{label:headers[4]||'المهارات السريرية',value:row[4]||'-'},{label:headers[5]||'المعرفة الطبية',value:row[5]||'-'},{label:headers[6]||'اتخاذ القرار',value:row[6]||'-'},{label:headers[7]||'المهارات الاجرائية',value:row[7]||'-'},{label:headers[8]||'العمل ضمن فريق',value:row[8]||'-'},{label:headers[9]||'المهنية والانضباط',value:row[9]||'-'},{label:headers[10]||'التواصل مع المرضى',value:row[10]||'-'},{label:headers[11]||'النشاطات الاكاديمية',value:row[11]||'-'}],total:row[12]||'-',praise:row[13]||'',penalty:row[14]||''}}}return null}
showMe(r){const rd=document.getElementById('myInfoResult');if(!rd)return;const ok=isJoined(r.st);this.currentMyInfo=r;
let myo=[];const tc={};for(const onc of this.oncRows){for(let col=2;col<this.oncHeaders.length;col++){const cc=(onc.row[col]||'').trim();if(!cc)continue;const names=splitNames(cc);if(!names.length)continue;const found=names.some(n=>exactNameMatch(n,r.abbr)||exactNameMatch(n,r.name));if(found){const cn=this.oncHeaders[col]||'أخرى';tc[cn]=(tc[cn]||0)+1;const colleagues=[];for(const n of names){if(!exactNameMatch(n,r.abbr)&&!exactNameMatch(n,r.name)){const cr=this.findRbyExact(n);if(cr)colleagues.push({name:cr.name,abbr:cr.abbr,phone:cr.phone});else colleagues.push({name:n,abbr:n,phone:''})}}myo.push({date:onc.date,day:onc.day||getDayName(onc.date),dayIdx:getDayIndex(onc.date),cat:cn,colleagues})}}}myo.sort((a,b)=>a.date.localeCompare(b.date));const tot=myo.length;const now=new Date();const ts=`${now.getFullYear()}-${String(now.getMonth()+1).padStart(2,'0')}-${String(now.getDate()).padStart(2,'0')} ${String(now.getHours()).padStart(2,'0')}:${String(now.getMinutes()).padStart(2,'0')}:${String(now.getSeconds()).padStart(2,'0')}`;const evalInfo=this.getEvalForResident(r.name,r.abbr);
let h=`<div id="myInfoContent" style="padding:8px;"><h3 style="color:#667eea;text-align:center;font-size:1.4em;margin-bottom:14px;"><i class="fas fa-user"></i> ${r.name} (${r.abbr}) <span style="font-size:0.6em;color:var(--text-secondary);">#${r.seq}</span></h3><div class="cumulative-box"><div class="cum-num">${r.cumulativeOnc||'0'}</div><div class="cum-lbl">إجمالي المناوبات التراكمية</div></div>`;
h+=`<div class="collapsible-section"><button class="collapsible-btn" onclick="toggleCollapsible(this)"><span><i class="fas fa-circle-info"></i> معلومات إضافية</span><i class="fas fa-chevron-down"></i></button><div class="collapsible-content"><div class="info-grid"><div class="info-item"><div class="info-label">الرقم التسلسلي</div><div class="info-value">${r.seq}</div></div><div class="info-item"><div class="info-label">الاختصاص</div><div class="info-value">${r.spec}</div></div><div class="info-item"><div class="info-label">الهاتف</div><div class="info-value"><span dir="ltr">${r.phone}</span> <button class="copy-btn" onclick="copyPhone('${r.phone}',this)"><i class="fas fa-copy"></i></button></div></div><div class="info-item"><div class="info-label">الالتحاق</div><div class="info-value">${r.join||'-'}</div></div><div class="info-item"><div class="info-label">الحالة</div><div class="info-value"><span class="status-badge ${ok?'status-joined':getStatusBadgeClass(r.st)}">${ok?'<i class="fas fa-circle-check"></i>':'<i class="fas fa-hourglass-half"></i>'} ${r.st||'غير محدد'}</span></div></div><div class="info-item"><div class="info-label">المناوبات الكلية</div><div class="info-value">${r.onc||'0'}</div></div></div></div></div>`;
if(evalInfo){h+=`<div class="collapsible-section"><button class="collapsible-btn" onclick="toggleCollapsible(this)"><span><i class="fas fa-chart-line"></i> التقييم السنوي</span><i class="fas fa-chevron-down"></i></button><div class="collapsible-content"><div class="info-grid">`;for(const skill of evalInfo.skills)h+=`<div class="info-item"><div class="info-label">${skill.label}</div><div class="info-value">${skill.value}</div></div>`;h+=`</div>`;if(evalInfo.praise&&evalInfo.praise.trim())h+=`<div style="margin-top:10px;padding:10px 14px;background:rgba(39,174,96,0.08);border-radius:10px;border-right:4px solid #27ae60;"><strong style="color:#27ae60;"><i class="fas fa-star"></i> الثناءات:</strong><br><span style="font-weight:600;color:#27ae60;">${evalInfo.praise}</span></div>`;if(evalInfo.penalty&&evalInfo.penalty.trim())h+=`<div style="margin-top:6px;padding:10px 14px;background:rgba(231,76,60,0.08);border-radius:10px;border-right:4px solid #e74c3c;"><strong style="color:#e74c3c;"><i class="fas fa-triangle-exclamation"></i> العقوبات:</strong><br><span style="font-weight:600;color:#e74c3c;">${evalInfo.penalty}</span></div>`;h+=`<div class="stat-card" style="margin-top:10px;"><div class="stat-num">${evalInfo.total}</div><div class="stat-lbl">المحصلة الاجمالية</div></div></div></div>`;}
const allMonths=this.getAllShiftMonths();const cm=this.getPreferredShiftMonth();h+=`<div class="collapsible-section"><button class="collapsible-btn open" onclick="toggleCollapsible(this)"><span><i class="fas fa-clipboard-list"></i> الفرز</span><i class="fas fa-chevron-down"></i></button><div class="collapsible-content show">`;if(allMonths.length>0){h+=`<div style="margin-bottom:12px;"><select class="month-selector" id="myInfoShiftMonth" onchange="app.updateMyInfoShift('${r.name.replace(/'/g,"\\'")}','${r.abbr.replace(/'/g,"\\'")}')">${allMonths.map(m=>`<option value="${m.month}"${m.month===cm?' selected':''}>${m.label||('فرز شهر '+m.month)}</option>`).join('')}</select></div><div id="myInfoShiftContent"></div>`}else{h+='<p style="color:#888;">لا توجد بيانات فروز.</p>'}h+='</div></div>';
h+=`<div class="collapsible-section"><button class="collapsible-btn open" onclick="toggleCollapsible(this)"><span><i class="fas fa-calendar-days"></i> المناوبات (${tot})</span><i class="fas fa-chevron-down"></i></button><div class="collapsible-content show">`;if(myo.length){h+=`<div class="capture-timestamp"><i class="fas fa-clock"></i> ${ts}</div><div style="display:grid;grid-template-columns:repeat(auto-fill,minmax(110px,1fr));gap:8px;margin-bottom:10px;"><div class="stat-card"><div class="stat-num">${tot}</div><div class="stat-lbl">إجمالي المناوبات</div></div>`;for(const[type,count]of Object.entries(tc).sort((a,b)=>b[1]-a[1]))h+=`<div class="stat-card"><div class="stat-num">${count}</div><div class="stat-lbl">${type}</div></div>`;h+='</div>';myo.forEach(o=>{const we=o.dayIdx===5||o.dayIdx===6;h+=`<div class="oncall-info-row"><div class="oc-header"><span class="oc-date${we?' weekend':''}">${we?'<span class="day-dot weekend"></span>':''}<i class="fas fa-calendar-day"></i> ${o.date} - ${o.day}</span><span class="oc-type">${o.cat}</span></div>`;if(o.colleagues.length){h+=`<div class="colleague-row"><span class="cl-label"><i class="fas fa-users"></i> الزملاء:</span><span class="cl-names">${o.colleagues.map((c,i)=>`${i>0?'<span class="cl-sep"> - </span>':''}${mcn(c.name,c.phone,c.abbr)}`).join('')}</span></div>`}h+='</div>'})}else h+='<p style="color:#888;">لا توجد مناوبات مسجلة هذا الشهر.</p>';h+='</div></div>';
h+=`<button class="download-btn" onclick="app.downloadMyInfoImage()"><i class="fas fa-camera btn-icon"></i><span class="btn-spinner"></span> تحميل معلوماتي كصورة</button></div>`;rd.innerHTML=h;rd.classList.add('show');document.getElementById('searchResultsList').innerHTML='';
setTimeout(()=>this.updateMyInfoShift(r.name,r.abbr),100)}
updateMyInfoShift(name,abbr){const cont=document.getElementById('myInfoShiftContent');if(!cont)return;const sel=document.getElementById('myInfoShiftMonth');if(!sel)return;const month=parseInt(sel.value);const h=this._resHeaders||[];const idx=this.getShiftColIndex(h,month);
if(idx<0||!this._resRaw||this._resRaw.length<2||this.isFutureShiftMonthAutoCopy(month)){cont.innerHTML='<p style="color:#888;">لا توجد بيانات لهذا الشهر.</p>';return}
const shiftVal=(this._resRaw.find(r=>r&&(r[1]||'').trim()===name)||[])[idx]||'';const shiftName=shiftVal.trim();
const members=[];for(let i=1;i<this._resRaw.length;i++){const r=this._resRaw[i];if(!r||!r[1])continue;const status=(r[11]||'').trim();if(!isJoined(status))continue;const sv=(r[idx]||'').trim();if(sv===shiftName&&sv&&sv!=='غير محدد'){const mname=(r[1]||'').trim();const mabbr=(r[2]||'').trim();const mphone=(r[4]||'').trim();if(!exactNameMatch(mabbr,abbr)&&!exactNameMatch(mname,name))members.push({name:mname,abbr:mabbr,phone:mphone})}}
let ht='';if(shiftName&&shiftName!=='غير محدد'){ht+=`<div class="shift-card-full" style="margin-bottom:10px;"><h3>${shiftName}</h3></div>`}else{ht+='<p style="color:#888;margin-bottom:10px;">لا يوجد فرز للشهر المحدد.</p>'}
if(members.length>0){ht+=`<div class="names-dropdown" style="margin-top:8px;"><button class="names-dropdown-btn"><span><i class="fas fa-users"></i> الزملاء في نفس الفرز (${members.length})</span><i class="fas fa-chevron-down"></i></button><ul class="names-dropdown-content">${members.map(m=>`<li>${mcn(m.name,m.phone,m.abbr)}</li>`).join('')}</ul></div>`}
cont.innerHTML=ht}
updateTime(){const el=document.getElementById('lastUpdateTime');if(el)el.textContent='آخر تحديث: '+new Date().toLocaleTimeString('ar-SA')}
}
let app;document.addEventListener('DOMContentLoaded',()=>{app=new HospitalApp();window.app=app});
