
function toggleDarkMode(){document.body.classList.toggle('dark-mode');const i=document.getElementById('darkModeIcon');if(document.body.classList.contains('dark-mode')){i.className='fas fa-sun';localStorage.setItem('darkMode','true')}else{i.className='fas fa-moon';localStorage.setItem('darkMode','false')}}
if(localStorage.getItem('darkMode')==='true'){document.body.classList.add('dark-mode');document.getElementById('darkModeIcon').className='fas fa-sun'}
let ttp='';
function showTooltip(e,nm,ph){e.stopPropagation();const tt=document.getElementById('nameTooltip');document.getElementById('ttName').textContent=nm;document.getElementById('ttPhone').textContent='هاتف: '+ph;ttp=ph;tt.classList.add('show');const x=e.clientX||(e.touches&&e.touches[0].clientX)||0;const y=e.clientY||(e.touches&&e.touches[0].clientY)||0;tt.style.left=Math.min(x-100,window.innerWidth-220)+'px';tt.style.top=(y-110)+'px'}
function hideTooltip(){document.getElementById('nameTooltip').classList.remove('show')}
function copyTooltipPhone(){if(ttp){navigator.clipboard.writeText(ttp);const b=document.getElementById('ttCopyBtn');b.innerHTML='<i class="fas fa-check"></i> تم النسخ';showToast('تم نسخ الرقم!');setTimeout(()=>b.innerHTML='<i class="fas fa-copy"></i> نسخ الرقم',1500)}}
document.addEventListener('click',e=>{if(!e.target.closest('.name-clickable')&&!e.target.closest('.name-tooltip'))hideTooltip()});
function copyPhone(p,b){navigator.clipboard.writeText(p).then(()=>{const i=b.querySelector('i');const o=i.className;i.className='fas fa-check';b.classList.add('copied');showToast('تم نسخ الرقم!');setTimeout(()=>{i.className=o;b.classList.remove('copied')},1500)}).catch(()=>{})}
function toggleCollapsible(btn){btn.classList.toggle('open');const c=btn.nextElementSibling;if(c)c.classList.toggle('show')}
function toggleQACard(card){card.classList.toggle('open')}
function toggleQACategory(h){h.classList.toggle('open');const c=h.nextElementSibling;if(c)c.classList.toggle('show')}
document.addEventListener('click',e=>{const db=e.target.closest('.names-dropdown-btn');if(db){e.stopPropagation();db.classList.toggle('open');const c=db.nextElementSibling;if(c)c.classList.toggle('show')}else{const dd=e.target.closest('.names-dropdown');if(!dd){document.querySelectorAll('.names-dropdown-btn.open').forEach(b=>{b.classList.remove('open');const c=b.nextElementSibling;if(c)c.classList.remove('show')})}}});
function showToast(m){const t=document.createElement('div');t.className='toast';t.textContent=m;document.body.appendChild(t);setTimeout(()=>t.remove(),2000)}
function showDownloadProgress(t){const o=document.getElementById('downloadProgressOverlay');document.getElementById('dpTitle').textContent=t||'جاري توليد الصورة...';document.getElementById('dpBar').style.width='0%';document.getElementById('dpPercent').textContent='0%';document.getElementById('dpSub').textContent='';o.classList.remove('hidden')}
function updateDownloadProgress(p,s){document.getElementById('dpBar').style.width=p+'%';document.getElementById('dpPercent').textContent=Math.round(p)+'%';if(s)document.getElementById('dpSub').textContent=s}
function hideDownloadProgress(){document.getElementById('downloadProgressOverlay').classList.add('hidden')}
function debounce(fn,wait=120){let t;return(...a)=>{clearTimeout(t);t=setTimeout(()=>fn(...a),wait)}}
function normAr(t){if(!t)return'';let r=t.toLowerCase().trim();r=r.replace(/[أإآا]/g,'ا');r=r.replace(/ؤ/g,'و');r=r.replace(/ئ/g,'ي');r=r.replace(/ى/g,'ا');r=r.replace(/ة/g,'ه');r=r.replace(/\bال/g,'');r=r.replace(/^ال/,'');r=r.replace(/[\u064B-\u0652]/g,'');r=r.replace(/\s+/g,' ').trim();return r}
function prepSearch(t){return normAr(t)}
function exactNameMatch(a,b){if(!a||!b)return false;const n1=a.trim(),n2=b.trim();if(n1===n2)return true;const nn1=normAr(n1),nn2=normAr(n2);if(nn1===nn2)return true;return nn1.replace(/[.\s]/g,'')===nn2.replace(/[.\s]/g,'')}
function splitNames(t){if(!t)return[];let lines=t.split(/[\n\r]+/);let r=[];for(let l of lines){l=l.trim();if(!l)continue;let sp=l.split(/[-–—,،;؛\/\\|]+/);for(let s of sp){s=s.trim();if(s)r.push(s)}}return r}
function smartSearch(t,s){if(!s)return true;const nt=prepSearch(t),ns=prepSearch(s);const sw=ns.split(/\s+/).filter(w=>w.length>0);if(!sw.length)return true;return sw.every(w=>nt.includes(w))}
function extractDate(t){if(!t)return null;let c=t.replace(/السبت|الأحد|الاثنين|الثلاثاء|الأربعاء|الخميس|الجمعة|Saturday|Sunday|Monday|Tuesday|Wednesday|Thursday|Friday/gi,'');c=c.replace(/[\u0660-\u0669]/g,ch=>String.fromCharCode(ch.charCodeAt(0)-0x0660+0x30));c=c.replace(/[٠-٩]/g,ch=>String.fromCharCode(ch.charCodeAt(0)-0x0660+0x30));let m=c.match(/(\d{4})-(\d{1,2})-(\d{1,2})/);if(m)return`${m[1]}-${m[2].padStart(2,'0')}-${m[3].padStart(2,'0')}`;m=c.match(/(\d{1,2})[\/\-.](\d{1,2})[\/\-.](\d{4})/);if(m)return`${m[3]}-${m[2].padStart(2,'0')}-${m[1].padStart(2,'0')}`;m=c.match(/(\d{1,2})[\/\-.](\d{1,2})[\/\-.](\d{2})/);if(m){const y=parseInt(m[3])<50?'20'+m[3]:'19'+m[3];return`${y}-${m[2].padStart(2,'0')}-${m[1].padStart(2,'0')}`}return null}
function getDayName(d){const dt=new Date(d+'T00:00:00');return isNaN(dt.getTime())?'':DAY_NAMES[dt.getDay()]}
function getDayIndex(d){const dt=new Date(d+'T00:00:00');return isNaN(dt.getTime())?-1:dt.getDay()}
function isWeekend(d){const i=getDayIndex(d);return i===5||i===6}
function isJoined(s){const st=(s||'').toLowerCase();return st.includes('التحق')||st.includes('ملتحق')||st.includes('التحاق')}
function getStatusBadgeClass(s){const st=normAr(s||'');if(st.includes('لم ينضم للغروب'))return 'status-not-joined';if(st.includes('لم يلتحق بعد'))return 'status-not-yet';return isJoined(s)?'status-joined':'status-pending'}
function mcn(nm,ph,ab){let d=nm;if(ab)d+=' ('+ab+')';if(!ph)return d;return`<span class="name-clickable" onclick="event.stopPropagation();showTooltip(event,'${nm.replace(/'/g,"\\'")}','${ph}')">${d}</span>`}
const SID='1Pb5VK1HsccaJpKXm-jersktd8yk4jf1V7o8qsDDmCI4';
const GID_R='0';const GID_O='238974679';const GID_E='253629565';const GID_L='1649404909';const GID_Q='680270268';
const AM=['كانون الثاني','شباط','آذار','نيسان','أيار','حزيران','تموز','آب','أيلول','تشرين الأول','تشرين الثاني','كانون الأول'];
const DAY_NAMES=['الأحد','الاثنين','الثلاثاء','الأربعاء','الخميس','الجمعة','السبت'];
const CK='hc_v62';const CD=10*60*1000;
const TABS=[{id:'residents',icon:'<i class="fas fa-user-doctor"></i>',label:'لائحة المقيمين'},{id:'shifts',icon:'<i class="fas fa-clipboard-list"></i>',label:'الفروز'},{id:'oncall',icon:'<i class="fas fa-calendar-days"></i>',label:'المناوبات'},{id:'evaluation',icon:'<i class="fas fa-chart-line"></i>',label:'التقييم السنوي'},{id:'links',icon:'<i class="fas fa-link"></i>',label:'روابط هامة'},{id:'myinfo',icon:'<i class="fas fa-id-card"></i>',label:'معلوماتي'},{id:'qa',icon:'<i class="fas fa-circle-question"></i>',label:'Q&A'}];
function buildNav(){return TABS.map(t=>`<button class="nav-btn" data-tab="${t.id}">${t.icon} <span>${t.label}</span></button>`).join('')}
function buildMainContent(){
return `<section class="tab-content active" id="residents-tab"><div class="section-header"><h2><i class="fas fa-users"></i> لائحة مقيمي السنة الأولى <span class="count-badge" id="residentCount">0</span><span class="percentage-badge" id="joinedPercentageBadge" style="display:none;"></span></h2></div><div class="controls-row" style="margin-bottom:12px"><div class="search-box"><input type="text" id="residentSearch" placeholder="ابحث باسم أو اختصار..."><i class="fas fa-search"></i></div></div><div class="controls-row" style="margin-bottom:12px"><select class="specialty-filter" id="specialtyFilter" onchange="app.filterBySpecialty()"><option value="">جميع الاختصاصات</option></select><select class="shift-filter" id="shiftFilter" onchange="app.filterByShift()"><option value="">جميع الفروز</option></select><button class="filter-btn" id="filterJoinedBtn" onclick="app.toggleFilter()"><i class="fas fa-filter"></i> الملتحقين فقط</button></div><div class="contacts-bar"><button class="select-all-btn" onclick="app.toggleSelectAll()"><i class="fas fa-check-square"></i> تحديد الكل</button><span class="selected-count" id="selectedCount">0 محدد</span><button class="contacts-btn" id="exportContactsBtn" onclick="app.exportToContacts()" disabled><i class="fas fa-address-book"></i> تحميل إلى جهات اتصالي</button></div><div class="table-wrapper desktop-table"><table><thead><tr><th style="width:35px">ت</th><th style="width:40px"><i class="fas fa-check"></i></th><th>الاسم الثلاثي</th><th>الاختصار</th><th>الاختصاص</th><th>الهاتف</th><th>الفرز</th><th>الالتحاق</th><th>المناوبات</th><th>الحالة</th></tr></thead><tbody id="residentsBody"></tbody></table></div><div class="mobile-cards" id="residentsCards"></div></section>
<section class="tab-content" id="shifts-tab"><div class="section-header"><h2><i class="fas fa-clipboard-list"></i> جدول فروز <span id="shiftMonthName"></span> <span class="shift-month-wrap"><span class="shift-month-label">الشهر</span><select class="month-selector" id="shiftsMonthSelector" onchange="app.changeShiftsMonth()"></select></span></h2><div class="search-box"><input type="text" id="shiftSearch" placeholder="ابحث باسم أو فرز..."><i class="fas fa-search"></i></div></div><div class="shifts-grid" id="shiftsGrid"></div></section>
<section class="tab-content" id="oncall-tab"><div class="section-header"><h2><i class="fas fa-calendar-check"></i> مناوبات شهر <span id="oncallMonthTitle"></span></h2></div><div class="oncall-controls"><label><i class="fas fa-calendar-day"></i> اختر تاريخ:</label><input type="date" id="oncallDatePicker" onchange="app.selectDayFromCalendar()"><select class="month-selector" id="monthSelector" onchange="app.changeMonth()">${AM.map((m,i)=>`<option value="${i}">${m}</option>`).join('')}</select></div><a class="oncall-link" href="https://docs.google.com/spreadsheets/d/${SID}/edit?gid=${GID_O}#gid=${GID_O}" target="_blank"><i class="fas fa-table-list"></i> لمشاهدة الجدول كامل اضغط هنا</a><div id="monthlyCalendar"></div><div id="oncallDayDisplay" style="margin-top:14px"></div></section>
<section class="tab-content" id="evaluation-tab"><div class="section-header"><h2><i class="fas fa-star"></i> التقييم السنوي للمقيمين</h2><div class="search-box"><input type="text" id="evalSearch" placeholder="ابحث باسم أو اختصار..."><i class="fas fa-search"></i></div></div><div class="table-wrapper desktop-table"><table><thead id="evalHead"></thead><tbody id="evalBody"></tbody></table></div><div class="mobile-cards" id="evalCards"></div></section>
<section class="tab-content" id="links-tab"><div class="section-header"><h2><i class="fas fa-link"></i> الروابط والقنوات الهامة</h2></div><div id="linksGrid"></div></section>
<section class="tab-content" id="myinfo-tab"><div class="section-header"><h2><i class="fas fa-user-search"></i> معلوماتي</h2><div class="search-box"><input type="text" id="myInfoSearch" placeholder="اكتب اسمك أو اختصارك..."><i class="fas fa-search"></i></div></div><div id="searchResultsList" class="search-results-list"></div><div id="myInfoResult" class="student-result"></div></section>
<section class="tab-content" id="qa-tab"><div class="section-header"><h2><i class="fas fa-question-circle"></i> الأسئلة والأجوبة</h2><div class="search-box"><input type="text" id="qaSearch" placeholder="ابحث في الأسئلة والأجوبة..."><i class="fas fa-search"></i></div></div><div id="qaContainer"></div></section>`;
}
