/**
 * Page skeleton — the nav buttons and every tab section, as HTML strings.
 *
 * Kept separate from the views so the markup of a tab and the code that fills it
 * are easy to find independently. `app.init()` injects both into index.html.
 */
(function (global) {
  'use strict';

  const AUH = global.AUH;
  const { TABS, MONTH_NAMES } = AUH.constants;

  /** The primary nav buttons. */
  function buildNav() {
    return TABS.map(t=>`<button class="nav-btn" data-tab="${t.id}">${t.icon} <span>${t.label}</span></button>`).join('');
  }

  /** All tab sections. Static WIP tabs are appended at runtime by the app. */
  function buildMainContent() {
    return `<section class="tab-content active" id="residents-tab"><div class="section-header"><h2><i class="fas fa-users"></i> لائحة مقيمي السنة الأولى <span class="count-badge" id="residentCount">0</span><span class="percentage-badge" id="joinedPercentageBadge" style="display:none;"></span></h2></div><div class="controls-row" style="margin-bottom:12px"><div class="search-box"><input type="text" id="residentSearch" placeholder="ابحث باسم أو اختصار..."><i class="fas fa-search"></i></div></div><div class="controls-row" style="margin-bottom:12px"><select class="specialty-filter" id="specialtyFilter" onchange="app.filterBySpecialty()"><option value="">جميع الاختصاصات</option></select><select class="shift-filter" id="shiftFilter" onchange="app.filterByShift()"><option value="">جميع الفروز</option></select><button class="filter-btn" id="filterJoinedBtn" onclick="app.toggleFilter()"><i class="fas fa-filter"></i> الملتحقين فقط</button><button class="filter-btn detached-filter-btn" id="filterDetachedBtn" onclick="app.toggleDetachedFilter()"><i class="fas fa-user-slash"></i> المنفكين 0</button></div><div class="contacts-bar"><button class="select-all-btn" onclick="app.toggleSelectAll()"><i class="fas fa-check-square"></i> تحديد الكل</button><span class="selected-count" id="selectedCount">0 محدد</span><button class="contacts-btn" id="exportContactsBtn" onclick="app.exportToContacts()" disabled><i class="fas fa-address-book"></i> تحميل إلى جهات اتصالي</button></div><div class="table-wrapper desktop-table"><table><thead><tr><th style="width:35px">ت</th><th style="width:40px"><i class="fas fa-check"></i></th><th>الاسم الثلاثي</th><th>الاختصار</th><th>الاختصاص</th><th>الهاتف</th><th>الفرز</th><th>الالتحاق</th><th>المناوبات</th><th>الحالة</th></tr></thead><tbody id="residentsBody"></tbody></table></div><div class="mobile-cards" id="residentsCards"></div></section>
  <section class="tab-content" id="lectures-tab"><div class="section-header"><h2><i class="fas fa-calendar-check"></i> رزنامة المحاضرات والانشطة الطبية</h2><div class="search-box"><input type="text" id="lecturesSearch" placeholder="ابحث بعنوان المحاضرة أو المحتويات أو المحاضر..."><i class="fas fa-search"></i></div></div><div class="controls-row" style="margin-bottom:12px"><select class="specialty-filter" id="lecturesCategoryFilter" onchange="app.filterLecturesByCategory()"><option value="">كل التصنيفات</option></select><select class="specialty-filter" id="lecturesDeptFilter" onchange="app.filterLecturesByDept()"><option value="">كل الأقسام</option></select><select class="shift-filter" id="lecturesYearFilter" onchange="app.filterLecturesByYear()"><option value="">كل السنوات</option></select><button class="filter-btn" id="lecturesPastBtn" onclick="app.togglePastLectures()"><i class="fas fa-clock-rotate-left"></i> رؤية المحاضرات القديمة</button></div><div class="lectures-calendar-shell"><div class="lectures-calendar-head"><button class="filter-btn lectures-cal-nav" aria-label="الشهر السابق" onclick="app.changeLecturesCalendarMonth(-1)"><i class="fas fa-chevron-right"></i></button><h3 id="lecturesCalendarTitle"></h3><button class="filter-btn lectures-cal-nav" aria-label="الشهر التالي" onclick="app.changeLecturesCalendarMonth(1)"><i class="fas fa-chevron-left"></i></button></div><div id="lecturesMonthlyCalendar" class="lectures-monthly-calendar"></div></div><div id="lecturesSelectedDayBox" class="lectures-selected-day"></div><div class="lectures-section-head lectures-today-head"><h3><i class="fas fa-star"></i> محاضرات اليوم</h3></div><div id="todayLecturesHero" class="today-lectures-hero"></div><div class="lectures-section-head"><h3><i class="fas fa-calendar-plus"></i> المحاضرات القادمة</h3></div><div id="upcomingLecturesList" class="lectures-grid"></div><div id="pastLecturesWrap" style="display:none;"><div class="lectures-section-head"><h3><i class="fas fa-calendar-minus"></i> المحاضرات القديمة</h3></div><div id="pastLecturesList" class="lectures-grid"></div></div></section>
  <section class="tab-content" id="shifts-tab"><div class="section-header"><h2><i class="fas fa-clipboard-list"></i> جدول فروز <span id="shiftMonthName"></span> <span class="shift-month-wrap"><span class="shift-month-label">الشهر</span><select class="month-selector" id="shiftsMonthSelector" onchange="app.changeShiftsMonth()"></select></span></h2><div class="search-box"><input type="text" id="shiftSearch" placeholder="ابحث باسم أو فرز..."><i class="fas fa-search"></i></div></div><div class="shifts-grid" id="shiftsGrid"></div></section>
  <section class="tab-content" id="oncall-tab"><div class="section-header"><h2><i class="fas fa-calendar-check"></i> مناوبات شهر <span id="oncallMonthTitle"></span></h2></div><div class="oncall-year-filter" id="oncallYearFilter"><button type="button" class="oncall-year-btn active" data-year="y1" onclick="app.changeOncallYearFilter('y1')">السنة الأولى</button><button type="button" class="oncall-year-btn" data-year="y2" onclick="app.changeOncallYearFilter('y2')">السنة الثانية</button><button type="button" class="oncall-year-btn" data-year="y1y2" onclick="app.changeOncallYearFilter('y1y2')">الأولى + الثانية</button></div><div class="oncall-controls"><label><i class="fas fa-calendar-day"></i> اختر تاريخ:</label><input type="date" id="oncallDatePicker" onchange="app.selectDayFromCalendar()"><span class="month-stepper"><button type="button" class="cal-nav-btn" aria-label="الشهر السابق" title="الشهر السابق" onclick="app.stepOncallMonth(-1)"><i class="fas fa-chevron-right"></i></button><select class="month-selector" id="monthSelector" onchange="app.changeMonth()">${MONTH_NAMES.map((m,i)=>`<option value="${i}">${m}</option>`).join('')}</select><button type="button" class="cal-nav-btn" aria-label="الشهر التالي" title="الشهر التالي" onclick="app.stepOncallMonth(1)"><i class="fas fa-chevron-left"></i></button></span><button class="filter-btn" onclick="app.toggleOncallRawTable()"><i class="fas fa-table"></i> عرض كجدول</button></div><div id="oncallRawTableWrap" class="oncall-raw-wrap" style="display:none;"></div><div id="monthlyCalendar"></div><div id="oncallDayDisplay" style="margin-top:14px"></div></section>
  <section class="tab-content" id="doctorstats-tab"><div class="section-header"><h2><i class="fas fa-chart-column"></i> احصائيات الأطباء <span class="count-badge" id="doctorStatsCount">0</span></h2><div class="search-box"><input type="text" id="doctorStatsSearch" placeholder="ابحث باسم الطبيب أو اختصاره..."><i class="fas fa-search"></i></div></div><div class="doctor-sort-panel"><div class="doctor-sort-control"><label for="doctorStatsSortMetric"><i class="fas fa-sort"></i> ترتيب حسب:</label><select id="doctorStatsSortMetric" onchange="app.setDoctorStatsSortMetric(this.value)"><option value="hoursCompleted">عدد الساعات (المناوبات التي تمّت)</option><option value="hoursTotal">عدد الساعات التراكمية</option><option value="total">عدد المناوبات</option><option value="praiseCount">عدد الثناءات</option><option value="bonusHours">ساعات Bonus</option><option value="emergency">عدد مناوبات الاسعاف</option><option value="holiday">عدد مناوبات العطل</option></select><button class="filter-btn" id="doctorStatsSortDirBtn" onclick="app.toggleDoctorStatsSortDir()"><i class="fas fa-arrow-down-wide-short"></i> تنازلي</button></div><button class="filter-btn excel-export-btn" onclick="app.downloadDoctorStatsExcel()"><i class="fas fa-file-excel"></i> تحميل كملف إكسل</button></div><div class="doctor-stats-grid" id="doctorStatsGrid"></div></section>
  <section class="tab-content" id="evaluation-tab"><div class="section-header"><h2><i class="fas fa-star"></i> التقييم السنوي للمقيمين</h2><div class="search-box"><input type="text" id="evalSearch" placeholder="ابحث باسم أو اختصار..."><i class="fas fa-search"></i></div></div><div class="table-wrapper desktop-table"><table><thead id="evalHead"></thead><tbody id="evalBody"></tbody></table></div><div class="mobile-cards" id="evalCards"></div></section>
  <section class="tab-content" id="links-tab"><div class="section-header"><h2><i class="fas fa-link"></i> الروابط والقنوات الهامة</h2></div><div id="linksGrid"></div></section>
  <section class="tab-content" id="myinfo-tab"><div class="section-header"><h2><i class="fas fa-user-search"></i> معلوماتي</h2><div class="search-box"><input type="text" id="myInfoSearch" placeholder="اكتب اسمك أو اختصارك..."><i class="fas fa-search"></i></div></div><div class="myinfo-hint">قم بكتابة اسمك في مربع البحث ليظهر لك معلوماتك (الفرز - المناوبات - التقييم - الاحصائيات ...)</div><div id="searchResultsList" class="search-results-list"></div><div id="myInfoResult" class="student-result"></div></section>
  <section class="tab-content" id="qa-tab"><div class="section-header"><h2><i class="fas fa-question-circle"></i> الأسئلة والأجوبة</h2><div class="search-box"><input type="text" id="qaSearch" placeholder="ابحث في الأسئلة والأجوبة..."><i class="fas fa-search"></i></div></div><div id="qaContainer"></div></section>
  <section class="tab-content" id="complaints-tab"><div class="section-header"><h2><i class="fas fa-triangle-exclamation"></i> الشكاوي</h2></div><div class="student-result" style="display:block;"><div class="student-body"><div class="complaint-primary">اذا كانت هناك اي مشاكل إدارية يرجى التواصل<br>د. محمد عدنان طرابيشي<br>وتس 0964515974<br>تلغرام Adnan_Tarabishi@<br>وشكرا</div><hr style="margin:14px 0;border:none;border-top:1px solid var(--border);"><div class="student-header"><h3 style="margin:0 auto;text-align:center;">اذا كانت هناك اي مشاكل تقنية يرجى التواصل</h3></div><div class="info-row"><i class="fas fa-user"></i><strong>علي شايب</strong></div><div class="info-row"><i class="fab fa-whatsapp"></i> وتس 0983893299</div><div class="info-row"><i class="fab fa-telegram"></i> تلغرام @ALI15cha</div><div class="info-row" style="justify-content:center;font-weight:700;">وشكرا</div></div></div></section>`;
  }

  AUH.views.layout = { buildNav, buildMainContent };
})(typeof window !== 'undefined' ? window : globalThis);
